version: '3.7'
services:

  fhir:
    build:
      context: .
      dockerfile: Dockerfile-ol
    hostname: fhir
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 2
      # https://docs.docker.com/compose/compose-file/#variable-substitution
      test: curl -v -f -k -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/$$healthcheck'
    ports:
      - 9443:9443

  db2:
    build:
      context: .
      dockerfile: Dockerfile-db2
    hostname: db2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=change-password
    ports:
      - 50000:50000
