name: Main Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build samples
      run: mvn -T2C install --file fhir-examples/pom.xml
    - name: Build parent with tests
      run: mvn -T2C package --file fhir-parent/pom.xml
