name: Server Integration Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build samples
      run: mvn -T2C install --file fhir-examples/pom.xml
    - name: Build parent without tests
      run: mvn -T2C install --file fhir-parent/pom.xml -DskipTests
    - name: Server Integration Tests
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        build/pre-integration-test.sh
        mvn test -DskipTests=false -f fhir-server-test/pom.xml
        build/post-integration-test.sh
